# Generated by Django 5.2.1 on 2025-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriBite', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriterecipe',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='spoonacular_id',
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='fdc_id',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
