# Generated by Django 5.2.1 on 2025-05-15 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriBite', '0003_rename_created_favoriterecipe_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='mealdb_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='fdc_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='favoriterecipe',
            unique_together={('user', 'fdc_id'), ('user', 'mealdb_id')},
        ),
    ]
